** Hi there! Thanks for checking out my profile!
My GitHub is primarily used as my playground to learn and test new tools and
technologies. If you would like to learn more about me go to [[https://www.ethancpost.com][my website]]. If you
feel that you can learn anything from me or the things I have learned, I
publicly publish all of the notes I have ever made: [[https://notes.ethancpost.com][here]].

If you would like a copy of my Resume you can find it here:
[[https://github.com/maker2413/maker2413/blob/master/Resume.pdf][PDF]]

- 💬 Ask me about emacs and I'll talk your ear off.
- 📫 How to reach me: [[ethancpost@gmail.com]]
- 🌱 I’m currently learning about Neural Networks and GoLang
# - 🔭 I’m currently working on ...
# - 👯 I’m looking to collaborate on ...
# - 🤔 I’m looking for help with ...
# - ⚡ Fun fact: ...
# -->

** My Skills
#+BEGIN_HTML
<h3 align="center">Languages</h3>
<p align="center">
  <a href="https://go.dev/"><img src="https://img.shields.io/badge/go-%2300ADD8.svg?style=for-the-badge&logo=go&logoColor=white" /></a>
  <a href="https://www.python.org/"><img src="https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54" /></a>
  <a href="https://www.gnu.org/software/emacs/manual/html_node/elisp/"><img src="https://img.shields.io/badge/Elisp-purple?style=for-the-badge&logo=gnuemacs&logoColor=white" /></a>
  <a href="https://www.typescriptlang.org/"><img src="https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white" /></a>
  <a href="https://www.gnu.org/software/bash/"><img src="https://img.shields.io/badge/bash_script-%23121011.svg?style=for-the-badge&logo=gnu-bash&logoColor=white" /></a>
</p>
#+END_HTML

#+BEGIN_HTML
<h3 align="center">Tools</h3>
<p align="center">
  <a href="https://kubernetes.io/"><img src="https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=for-the-badge&logo=kubernetes&logoColor=white" /></a>
  <a href="https://www.terraform.io/"><img src="https://img.shields.io/badge/terraform-%235835CC.svg?style=for-the-badge&logo=terraform&logoColor=white" /></a>
  <a href="https://www.docker.com/"><img src="https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white" /></a>
  <a href="https://www.ansible.com/"><img src="https://img.shields.io/badge/ansible-%231A1918.svg?style=for-the-badge&logo=ansible&logoColor=white" /></a>
  <a href="https://argo-cd.readthedocs.io/en/stable/"><img src="https://img.shields.io/badge/argo_cd-%23EF7B4D?style=for-the-badge&logo=argo&logoColor=white" /></a>
  <a href="https://github.com/features/actions"><img src="https://img.shields.io/badge/github%20actions-%232671E5.svg?style=for-the-badge&logo=githubactions&logoColor=white" /></a>
</p>
#+END_HTML

#+BEGIN_HTML
<h3 align="center">Cloud</h3>
<p align="center">
  <a href="https://aws.amazon.com/"><img src="https://img.shields.io/badge/AWS-%23FF9900?style=for-the-badge&logo=amazonwebservices&logoColor=%23232F3E" /></a>
  <a href="https://cloud.google.com/"><img src="https://img.shields.io/badge/GoogleCloud-%234285F4.svg?style=for-the-badge&logo=google-cloud&logoColor=white" /></a>
</p>
#+END_HTML

* Boot.dev
  You can also find me [[https://www.boot.dev/u/maker2413][Boot.Dev]]. I also will include all of my certs from
  BootDev: [[./BootDevCerts/][here]]

* Completed Courses
  I'm not sure where else to store these, but [[./UdemyCerts/][here]] are the Udemy courses I have
  completed.
